url: https://juhaniemi.github.io
baseurl: /brothergood/

# Site settings
title: Brothergood
email: brothergoodmusic@gmail.com
description: "Brothergood. Music that matters... To us."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Timo Niemi
  pic: 1
  position: Lead Vocals, Lyrics
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Juha Niemi
  pic: 2
  position: Composing, Producer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thebrothergood
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Turku, Finland

# Build settings
markdown: kramdown
permalink: pretty