url: http://www.brothergood.net
baseurl: 

# Site settings
title: Brothergood
email: brothergoodmusic@gmail.com
description: "Brothergood. Music that matters... To us."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thebrothergood
  - title: facebook
    url: http://www.facebook.com/brothergoodmusic

# Postal address (add as many lines as necessary)
address:
  - line: Turku, Finland

# Build settings
markdown: kramdown
permalink: pretty
